---
title: "Case Study 1 - US Breweries"
author: "Brychan Manry and Patricia Goresen"
date: "October 23, 2017"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(kableExtra)
library(knitr)
library(ggplot2)
library(ggthemes)
```

## Ingest Data
```{r dataingest}
beers <- read.csv("./rawdata/Beers.csv") %>% rename(Beer_Name = Name)
breweries <- read.csv("./rawdata/Breweries.csv") %>% rename(Brewery_Name = Name)

```


## Q1
```{r q1}

```


## Q2
```{r q2}
beers <- merge(beers, breweries, by.x = "Brewery_id", by.y = "Brew_ID")

```

## Q3
```{r q3}

```

## Q4
```{r q4, fig.width=11}
# Median ABV and IBU by State Alpha
ggplot(
  bind_rows(
    beers %>% select(State, val = ABV) %>% mutate(var = "ABV"),
    beers %>% select(State, val = IBU) %>% mutate(var = "IBU")) %>%
    group_by(State, var) %>%
    summarise(med.val = median(val, na.rm = TRUE)),
  aes(x = State, fill = var, group = var)) +
  geom_bar(aes(y = med.val), stat = "identity", position = "dodge") +
  facet_grid(var ~ ., scales = "free_y")

```

## Q5
```{r q5, fig.width=11}
# Median ABV by state - ordered by median
plot.df <- beers %>% group_by(State) %>% summarise(median.abv = median(ABV, na.rm = TRUE))
plot.df$State <- factor(plot.df$State, levels = plot.df$State[order(plot.df$median.abv, decreasing = TRUE)])
ggplot(plot.df, aes(State, y = median.abv)) + geom_bar(stat = "identity")

# Median IBU by state - ordered by median
plot.df <- beers %>% group_by(State) %>% summarise(median.ibu = median(IBU, na.rm = TRUE))
plot.df$State <- factor(plot.df$State, levels = plot.df$State[order(plot.df$median.ibu, decreasing = TRUE)])
ggplot(plot.df, aes(State, y = median.ibu)) + geom_bar(stat = "identity")


```

## Q6
```{r q6}

```

## Q7
```{r q7}
ggplot(beers, aes(IBU, ABV))+
  geom_point() +
  geom_smooth(method = "lm")

pander::pander(summary(lm(ABV ~ IBU, data = beers)))

```










